### ISSUE TITLE
Highliting member tags and tag parameters

### ISSUE THREAD

**Issue by MrMacvos** [bfad/Sublime-Lasso#1]
Currently member tags and tag parameters are colored in black. I could not find a setting for them to use in a theme. Would it be possible to implement this?

Thanks!

**Comment by bfad** [comment]
I think I could probably figure out how to do this. It sounds to me like we need a regular expression that consists of "->" or "&" followed by any amount of whitespace before the method name. I can't think of any other syntactical features that would conflict with, can you?

**Comment by MrMacvos** [comment]
Ah, the & is good one! One possible conflict could be with && where the regex would see the second & as the retarget symbol.

**Comment by bfad** [comment]
This is not a feature I would find useful. Combine that with the complexity of getting it right, and I don't have the time to add this feature. If someone has added this and wants to send me a pull request, I would entertain merging it into the code base
